03-homework
ArtemCh101/MachineLearningHSE pull request #5
Opened 2024-03-15 16:01 UTC by ArtemCh101

2024-03-16 12:50 UTC, svkov requested changes
Пока 0. В easy нет классов, которые модель часто путает. В medium не все модели обучены.

2024-03-16 12:50 UTC, svkov commented on notebooks/03-homework.ipynb
> +    ", но Accuracy_score тоже посмотрим, так как это универсальная метрика для задач классификации"
accuracy тут нельзя использовать, рассказывал на последней лекции почему

2024-03-16 12:50 UTC, svkov commented on notebooks/03-homework.ipynb
> +    "Не вполне уверен в том, почему именно эта модель справилась хуже всего(думал худшей окажется KNN в силу ее простоты). Могу предположить, что это свзяано с неоптимальными гиперпараметрами, в след
knn хоть и простая модель, но обычно работает неплохо
не вижу обученного байесовского классификатора

2024-03-22 13:34 UTC, closed without merging

2024-03-22 20:53 UTC, ArtemCh101 commented
https://github.com/ArtemCh101/MachineLearningHSE/pull/6

сб, 16 мар. 2024 г. в 15:50, Святослав ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Пока 0. В easy нет классов, которые модель часто путает. В medium не все
> модели обучены.
> ------------------------------
>
> In notebooks/03-homework.ipynb
> <https://github.com/ArtemCh101/MachineLearningHSE/pull/5#discussion_r1527168663>
> :
>
> > +     "metadata": {},
> +     "output_type": "execute_result"
> +    }
> +   ],
> +   "source": [
> +    "model_SVC_rbf = SVC(kernel='rbf')\n",
> +    "model_SVC_rbf.fit(x_train, y_train)"
> +   ]
> +  },
> +  {
> +   "cell_type": "markdown",
> +   "id": "13d9509c",
> +   "metadata": {},
> +   "source": [
> +    "Будем использовать Recall_score, так как цена нераспознования верного знака очень высока\n",
> +    ", но Accuracy_score тоже посмотрим, так как это универсальная метрика для задач классификации"
>
> accuracy тут нельзя использовать, рассказывал на последней лекции почему
> ------------------------------
>
> In notebooks/03-homework.ipynb
> <https://github.com/ArtemCh101/MachineLearningHSE/pull/5#discussion_r1527168744>
> :
>
> > +   "source": [
> +    "y_pred = model_SVC_rbf.predict(x_test)\n",
> +    "print(\"SVC_rbf Accuracy_score is:\",accuracy_score(y_test,y_pred))\n",
> +    "print(\"SVC_rbf Recall_score   is:\",recall_score(y_test,y_pred,average='macro'))"
> +   ]
> +  },
> +  {
> +   "cell_type": "markdown",
> +   "id": "857b26ad",
> +   "metadata": {},
> +   "source": [
> +    "Лучше всего с задачей справилась модель: SVC_linear\n",
> +    "\n",
> +    "Хуже всего с задачей справилась модель: SVC_poly\n",
> +    "\n",
> +    "Не вполне уверен в том, почему именно эта модель справилась хуже всего(думал худшей окажется KNN в силу ее простоты). Могу предположить, что это свзяано с неоптимальными гиперпараметрами, в следствии чего данная модель недообучилась(дефолтный degree = 3) или с тем, что наши данные распределены линейно(что можно понять из успеха использования линейного ядра данной модели)\n",
>
> knn хоть и простая модель, но обычно работает неплохо
> не вижу обученного байесовского классификатора
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ArtemCh101/MachineLearningHSE/pull/5#pullrequestreview-1941029948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2WVNYQ3JANR7OJ23VC476LYYQ52DAVCNFSM6AAAAABEYIG7BWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBRGAZDSOJUHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>